kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  namespace: argocd
  annotations:
    avp.kubernetes.io/path: "integ/argocd/samplesecret"
type: Opaque
stringData:
  test-secret: <createdby>
